name: NNNK club
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2  # 升级到最新版本
        with:
          persist-credentials: false
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install and Build
        run: |
          npm install
          npm run-script build
      - name: nishinokaede
        uses: nishinokaede/nnnkclub-website
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          folder: build
